name: Verify docker app

on:
  push:
    branches: ['main']
    paths:
      - 'projects/dockerize-python-application/**'
  pull_request:
    branches: ['main']
    paths:
      - 'projects/dockerize-python-application/**'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build the Docker image
        run: |
          cd projects/dockerize-python-application
          chmod +x demo_project.sh; ls -la
          ./demo_project.sh
